[project]
name = "topic-modeling-recommendation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<=3.13"
dependencies = [
    "pandas",
    "scikit-learn",
    "python-dotenv",
    "pypdf",
    "openai",
    # Core ML & NLP
    "sentence-transformers",
    "spacy",
    "spacy-transformers",
    "nltk",
    "pywsd",
    # Topic Modeling
    "contextualized-topic-models",
    "pyldavis",
    "gensim>=4.3.0",
    # LangChain
    "langchain-community",
    "langchain-openai",
    # Visualization & Notebook
    "matplotlib",
    "seaborn",
    "wordcloud",
    "ipykernel",
    # Other
    "lyricsgenius",
    "psutil>=7.0.0",
]
